# Generated by Django 3.1.7 on 2021-03-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-pub_date']},
        ),
    ]
