# Generated by Django 3.1.7 on 2021-03-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210329_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumb',
            field=models.FileField(blank=True, upload_to='thumb/'),
        ),
    ]
