# Generated by Django 3.1.7 on 2021-03-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='thumb',
        ),
    ]
